# Generated by Django 5.2.7 on 2025-10-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('place_id', models.CharField(max_length=255, unique=True)),
                ('details_url', models.CharField(max_length=255)),
                ('coordinates', models.JSONField()),
            ],
        ),
    ]
