# Generated by Django 5.2.7 on 2025-10-21 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ('title',), 'verbose_name': 'Место города', 'verbose_name_plural': 'Места города'},
        ),
        migrations.RemoveField(
            model_name='place',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='place',
            name='details_url',
        ),
        migrations.RemoveField(
            model_name='place',
            name='place_id',
        ),
        migrations.AddField(
            model_name='place',
            name='coordinates_lat',
            field=models.FloatField(default=12, verbose_name='Широта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='coordinates_lng',
            field=models.FloatField(default=12, verbose_name='Долгота'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='descriptiont',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='place',
            name='slug',
            field=models.SlugField(default=1, unique=True, verbose_name='Слаг'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.PositiveIntegerField(blank=True, verbose_name='Номер')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='place.place', verbose_name='Место')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ('order_num',),
            },
        ),
    ]
