# Generated by Django 5.2.7 on 2025-10-22 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_alter_place_options_remove_place_coordinates_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='descriptiont',
            new_name='description',
        ),
    ]
