# Generated by Django 5.2.7 on 2025-10-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_rename_descriptiont_place_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='order_num',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер'),
        ),
    ]
